[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.identity_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2IDENTITY_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
username = "wso2carbon"
password = "wso2carbon"

[database.shared_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
username = "wso2carbon"
password = "wso2carbon"

[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"

[user_store]
type = "read_write_ldap_unique_id"
connection_url = "ldap://openldap:389"
connection_name = "cn=admin,dc=copper,dc=opensource,dc=lk"
connection_password = "admin"
base_dn = "dc=copper,dc=opensource,dc=lk"
[user_store.properties]
EmptyRolesAllowed="false"

[keystore.internal]
file_name = "wso2carbon.jks"
type = "JKS"
password = "adminlsf"
alias = "wso2"
key_password = "adminlsf"